### ISSUE TITLE
Add support for Generator and AsyncGenerator

### ISSUE THREAD

**Issue by lxsmnsyc** [lxsmnsyc/seroval#31]

**Comment by ducan-ne** [comment]
Hi @lxsmnsyc I see this already implemented in code but is that not flagged ready to use?

Try to use it with solid start but seem like doesn't work

```typescript
export const logHello = async function (message: string) {
  'use server'
  console.log(message)

  return {
    title: 'Hello World',
    async* [Symbol.asyncIterator](): AsyncIterator<number> {
      await Promise.resolve()
      yield 1
      await new Promise((resolve) => setTimeout(resolve, 1000))
      yield 2
      await new Promise((resolve) => setTimeout(resolve, 5000))
      yield 3
    },
  }
}
```

```typescript
export const logHello = async function * (message: string) {
  "use server";
  console.log(message);

  yield { a: true }
  await new Promise((resolve) => setTimeout(resolve, 5000))

  yield { b: true }
};
```

**Comment by lxsmnsyc** [comment]
@ducan-ne Last time I've tested this this should work. Please provide more info.

**Comment by ducan-ne** [comment]
@lxsmnsyc 
The lastest version should happens
https://github.com/ducan-ne/solid-async-generator-reproduction/blob/main/src/actions.tsx
https://github.com/ducan-ne/solid-async-generator-reproduction/blob/main/src/components/Counter.tsx

`for await (const value of logHello('Hello')) {` not work either

Error

```
Uncaught (in promise) TypeError: logHello(...) is not a function or its return value is not async iterable

Or

Counter.tsx:20  Uncaught (in promise) {a: true}
````

**Comment by lxsmnsyc** [comment]
Okay I've tested this one, this isn't a Seroval problem. Please create an issue in SolidStart.

**Comment by ducan-ne** [comment]
Okay, thank for your infromation

**Comment by lxsmnsyc** [comment]
@theturtle32 are we talking about the last comment or the entire concept

**Comment by theturtle32** [comment]
The entire concept works fine for me.

**Comment by theturtle32** [comment]
I use server functions with async generators to return chunks of streaming chat-bot responses from the server to the client via seroval.

**Comment by theturtle32** [comment]
And it appears that the related bug in SolidStart was closed as completed on May 20th.

**Comment by lxsmnsyc** [comment]
@theturtle32 yep it's been resolved. This topic is originally for the fully support of Generators and AsyncGenerators (this also includes the `yield`) but got sidetracked

**Comment by theturtle32** [comment]
@lxsmnsyc This was working perfectly fine until the release of `v1.3.0`. I'm now getting client-side errors when trying to deserialize the streaming response of an async generator server function in SolidStart.

I was going to open a new issue to report the breakage, but then I noticed that this issue is still open for some reason?

Minimal SolidStart reproduction case follows. Note that generators as server functions broke when SolidStart switched to `@tanstack/server-functions-plugin`. That has been resolved upstream in `@tanstack/server-functions-plugin@1.119.2`. 

For relevant discussion see https://github.com/solidjs/solid-start/issues/1886 and for the fix in SolidStart see https://github.com/solidjs/solid-start/pull/1888

```typescript
/* src/server-functions.ts */

export async function* sayHello() {
  "use server";

  const greetings = [
    "Hello, World!",      // English
    "¡Hola, Mundo!",      // Spanish
    "Bonjour le monde !"  // French
  ];

  for (const greeting of greetings) {
    console.log(greeting);
    yield greeting;
    await new Promise(resolve => setTimeout(resolve, 1000)); // Wait for 1 second
  }
}
```

```typescript
/* src/routes/generator-server-fn.tsx */

import { Title } from "@solidjs/meta";
import { For, onMount } from "solid-js";
import { createStore } from "solid-js/store";
import { sayHello } from '~/server-functions';

export default function GeneratorServerFn() {
  const [store, setStore] = createStore<Array<string>>([]);

  onMount(async () => {
    const greetings = await sayHello();
    for await (const greeting of greetings) {
      setStore(store.length, greeting);
    }
  });

  return (
    <main>
      <Title>Generator Server Fn</Title>
      <h1>Generator Server Fn</h1>
      <For each={store}>
        {(message) => <div class="message">{message}</div>}
      </For>
    </main>
  );
}
```

Each time the client tries to parse the data returned from the server function, I get these two exceptions in the console:
```
VM325:1 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 's')
    at eval (eval at deserialize (index.ts:47:14), <anonymous>:1:156)
    at new Promise (<anonymous>)
    at $R.<computed>.Object.assign.$R.<computed> (eval at deserialize (index.ts:47:14), <anonymous>:1:133)
    at Object.next (eval at deserialize (index.ts:47:14), <anonymous>:1:588)
    at generator-server-fn.tsx:11:22

VM325:1 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'p')
    at $R.<computed>.Object.assign.$R.<computed> (eval at deserialize (index.ts:47:14), <anonymous>:1:132)
    at Object.next (eval at deserialize (index.ts:47:14), <anonymous>:1:588)
    at generator-server-fn.tsx:11:22
```

The malfunctioning serialized JS returned from the server:
```javascript
;0x000004e9;
((self.$R = self.$R || {})["server-fn:0"] = [],
($R => $R[0] = Object.assign(Object.create(null), {
    [$R[1] = Symbol.asyncIterator]: (($R[3] = r => (r.p = new Promise( (s, f) => {
        r.s = s,
        r.f = f
    }
    )),
    $R[2] = s => (b, c, p, d, e, t, f) => (b = [],
    c = 0,
    p = [],
    d = -1,
    e = !1,
    f = (i, l) => {
        for (i = 0,
        l = p.length; i < l; i++)
            p[i].s({
                done: !0,
                value: void 0
            })
    }
    ,
    s.on({
        next: (v, t) => {
            if (t = p.shift())
                t.s({
                    done: !1,
                    value: v
                });
            b.push(v)
        }
        ,
        throw: (v, t) => {
            if (t = p.shift())
                t.f(v);
            f(),
            d = b.length,
            e = !0,
            b.push(v)
        }
        ,
        return: (v, t) => {
            if (t = p.shift())
                t.s({
                    done: !0,
                    value: v
                });
            f(),
            d = b.length,
            b.push(v)
        }
    }),
    t = {
        [$R[1]]: () => t,
        next: (i, t, v) => {
            if (d === -1) {
                return ((i = c++) >= b.length) ? (p.push(t = $R[3]()),
                t) : {
                    done: !1,
                    value: b[i]
                }
            }
            if (c > d)
                return {
                    done: !0,
                    value: void 0
                };
            if (v = b[i = c++],
            i !== d)
                return {
                    done: !1,
                    value: v
                };
            if (e)
                throw v;
            return {
                done: !0,
                value: v
            }
        }
    })))($R[4] = ($R[5] = (b, a, s, l, p, f, e, n) => (b = [],
    a = !0,
    s = !1,
    l = [],
    p = 0,
    f = (v, m, x) => {
        for (x = 0; x < p; x++)
            l[x] && l[x][m](v)
    }
    ,
    n = (o, x, z, c) => {
        for (x = 0,
        z = b.length; x < z; x++)
            (c = b[x],
            (!a && x === z - 1) ? o[s ? "return" : "throw"](c) : o.next(c))
    }
    ,
    e = (o, t) => (a && (l[t = p++] = o),
    n(o),
    () => {
        a && (l[t] = void 0)
    }
    ),
    {
        __SEROVAL_STREAM__: !0,
        on: o => e(o),
        next: v => {
            a && (b.push(v),
            f(v, "next"))
        }
        ,
        throw: v => {
            a && (b.push(v),
            f(v, "throw"),
            a = s = !1,
            l.length = 0)
        }
        ,
        return: v => {
            a && (b.push(v),
            f(v, "return"),
            a = !1,
            s = !0,
            l.length = 0)
        }
    }))()),
    [$R[6] = Symbol.toStringTag]: "AsyncGenerator"
}))($R["server-fn:0"]));
0x00000034;
($R => $R[4].next("Hello, World!"))($R["server-fn:0"]);
0x00000035;
($R => $R[4].next("¡Hola, Mundo!"))($R["server-fn:0"]);
0x00000039;
($R => $R[4].next("Bonjour le monde !"))($R["server-fn:0"]);
0x0000002d;
($R => $R[4].return(void 0))($R["server-fn:0"])
```

Screenshot:

<img width="1624" alt="Image" src="https://github.com/user-attachments/assets/129b92c3-581e-4ee8-b247-1b2a8ea23e6a" />


I tried looking through the changes between v1.2.1 and v1.3.0 but I'm not familiar enough with the Seroval source code to really pinpoint the change that broke this.

Any thoughts/ideas? For now, I'm going to pin seroval at v1.2.1 in my project.

**Comment by lxsmnsyc** [comment]
@theturtle32 please make a new issue thread so it's easier to track.

**Comment by theturtle32** [comment]
Ok. Should we close this one then?

**Comment by theturtle32** [comment]
Opened #57

**Comment by lxsmnsyc** [comment]
@theturtle32 I'm not really closing this since this thread is for an entirely different goal. TBH this is the second time it's hijacked 🤣 but it's fine

**Comment by theturtle32** [comment]
Oh, what is the different goal? I've been confused then, because Seroval seems to already have support for Generator and AsyncGenerator.

**Comment by theturtle32** [comment]
I guess I might be conflating it with Iterator and AsyncIterator, kind of the flip side of the coin? Since an async generator function just returns an instance of `AsyncGenerator`, which is a subclass of `AsyncIterator`. Is there functionality more specific to the `AsyncGenerator` subclass that is still not yet handled?

**Comment by lxsmnsyc** [comment]
@theturtle32 yes, the two-way data of generators. `Iterator` instances are one-way. `Generator` instances are two-way.

```js
function* example() {
  
  console.log('Received', yield 'foo');
}

const gen = example();
gen.next(); // { value: 'foo', done: false }
gen.next('bar'); // logs 'Received bar'
```
